# Constants
FONT = 'Helvetica'
OUTPUT_FONT_SIZE = 50
NORMAL_FONT_SIZE = 25

INPUT_LENGTH_THRESHOLD = 6
RESULT_LENGTH_THRESHOLD = 20
INPUT_FONT_REDUCTION = 30
RESULT_FONT_REDUCTION = 10

SPACE = ' '
MATH_OPERATIONS = '+-*/'
